admin_admin_bundle_sonata_admin:
    resource: "@AdminAdminBundleSonataAdminBundle/Controller/"
    type:     annotation
    prefix:   /

iia_web_service:
    resource: "@IIAWebServiceBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#FOS USER
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#REST 
rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api

#SONATA
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
 
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin