iia_web_service:
    resource: "@IIAWebServiceBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#FOS USER
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#REST 
rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api

